/* tslint:disable */
/* eslint-disable */
/**
 * Fanno Platform API
 * AI-driven platform automation API for agent orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@fanno.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSessionResponse
 */
export interface CreateSessionResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponse
     */
    sessionId: string;
}

/**
 * Check if a given object implements the CreateSessionResponse interface.
 */
export function instanceOfCreateSessionResponse(value: object): value is CreateSessionResponse {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    return true;
}

export function CreateSessionResponseFromJSON(json: any): CreateSessionResponse {
    return CreateSessionResponseFromJSONTyped(json, false);
}

export function CreateSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'],
    };
}

export function CreateSessionResponseToJSON(json: any): CreateSessionResponse {
    return CreateSessionResponseToJSONTyped(json, false);
}

export function CreateSessionResponseToJSONTyped(value?: CreateSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionId': value['sessionId'],
    };
}

