/* tslint:disable */
/* eslint-disable */
/**
 * Fanno Platform API
 * AI-driven platform automation API for agent orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@fanno.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StripeWebhookEvent
 */
export interface StripeWebhookEvent {
    /**
     * 
     * @type {string}
     * @memberof StripeWebhookEvent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof StripeWebhookEvent
     */
    type: string;
    /**
     * Stripe event payload
     * @type {object}
     * @memberof StripeWebhookEvent
     */
    data: object;
}

/**
 * Check if a given object implements the StripeWebhookEvent interface.
 */
export function instanceOfStripeWebhookEvent(value: object): value is StripeWebhookEvent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function StripeWebhookEventFromJSON(json: any): StripeWebhookEvent {
    return StripeWebhookEventFromJSONTyped(json, false);
}

export function StripeWebhookEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripeWebhookEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'data': json['data'],
    };
}

export function StripeWebhookEventToJSON(json: any): StripeWebhookEvent {
    return StripeWebhookEventToJSONTyped(json, false);
}

export function StripeWebhookEventToJSONTyped(value?: StripeWebhookEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'data': value['data'],
    };
}

