
name: Run Frontend Agent

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: 'New payments SDK version'
        required: false
      design_system_version:
        description: 'New design system version'
        required: false
      webrtc_client_version:
        description: 'New WebRTC client version'
        required: false

jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update packages based on inputs
        run: |
          if [ -n "${{ github.event.inputs.sdk_version }}" ]; then
            echo "Updating payments SDK to ${{ github.event.inputs.sdk_version }}"
            npm install fanno-payments-workspace@${{ github.event.inputs.sdk_version }}
          fi
          
          if [ -n "${{ github.event.inputs.design_system_version }}" ]; then
            echo "Updating design system to ${{ github.event.inputs.design_system_version }}"
            npm install @fanno/design-system@${{ github.event.inputs.design_system_version }}
          fi
          
          if [ -n "${{ github.event.inputs.webrtc_client_version }}" ]; then
            echo "Updating WebRTC client to ${{ github.event.inputs.webrtc_client_version }}"
            npm install @fanno/webrtc-client@${{ github.event.inputs.webrtc_client_version }}
          fi

      - name: Run AI-powered scaffold step
        run: npx locofy generate --config locofy.config.js

      - name: Build project to verify changes
        run: npm run build

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          
          # Create commit message based on what was updated
          COMMIT_MSG="chore: update frontend dependencies"
          if [ -n "${{ github.event.inputs.sdk_version }}" ]; then
            COMMIT_MSG="$COMMIT_MSG - payments-sdk v${{ github.event.inputs.sdk_version }}"
          fi
          if [ -n "${{ github.event.inputs.design_system_version }}" ]; then
            COMMIT_MSG="$COMMIT_MSG - design-system v${{ github.event.inputs.design_system_version }}"
          fi
          if [ -n "${{ github.event.inputs.webrtc_client_version }}" ]; then
            COMMIT_MSG="$COMMIT_MSG - webrtc-client v${{ github.event.inputs.webrtc_client_version }}"
          fi
          
          git commit -m "$COMMIT_MSG" || echo "No changes to commit"
          git push
