
name: Run Frontend Agent

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: 'New payments SDK version'
        required: true

jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update payments SDK to ${{ github.event.inputs.sdk_version }}
        run: |
          npm install fanno-payments-workspace@${{ github.event.inputs.sdk_version }}

      - name: Run AI-powered scaffold step
        run: npx locofy generate --config locofy.config.js

      - name: Build project to verify changes
        run: npm run build

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: regenerate frontend with payments-sdk v${{ github.event.inputs.sdk_version }}" || echo "No changes to commit"
          git push
